import { buildOfflineTypes } from '../actions/helpers';

export const LIST_API_SEED_COMPANIES = buildOfflineTypes('LIST_API_SEED_COMPANIES');
export const CREATE_API_SEED_COMPANY_SUCCESS = 'CREATE_API_SEED_COMPANY_SUCCESS';
export const UPDATE_API_SEED_COMPANY_SUCCESS = 'UPDATE_API_SEED_COMPANY_SUCCESS';
export const DELETE_API_SEED_COMPANY_SUCCESS = 'DELETE_API_SEED_COMPANY_SUCCESS';
