import { buildOfflineTypes } from '../actions/helpers';

export const LIST_CUSTOMER_MONSANTO_PRODUCTS = buildOfflineTypes('LIST_CUSTOMER_MONSANTO_PRODUCTS');
export const CREATE_CUSTOMER_MONSANTO_PRODUCT_SUCCESS = 'CREATE_CUSTOMER_MONSANTO_PRODUCT_SUCCESS';
export const DELETE_CUSTOMER_MONSANTO_PRODUCT_SUCCESS = 'DELETE_CUSTOMER_MONSANTO_PRODUCT_SUCCESS';
export const UPDATE_CUSTOMER_MONSANTO_PRODUCT_SUCCESS = 'UPDATE_CUSTOMER_MONSANTO_PRODUCT_SUCCESS';
export const REMOVE_RECENT_CREATED_CUSTOMER_MONSANTO_PRODUCT = 'REMOVE_RECENT_CREATED_CUSTOMER_MONSANTO_PRODUCT';
