import { buildOfflineTypes } from '../actions/helpers';

export const LIST_CUSTOM_PRODUCTS = buildOfflineTypes('LIST_CUSTOM_PRODUCTS');
export const CREATE_CUSTOM_PRODUCT_SUCCESS = 'CREATE_CUSTOM_PRODUCT_SUCCESS';
export const DELETE_CUSTOM_PRODUCT_SUCCESS = 'DELETE_CUSTOM_PRODUCT_SUCCESS';
export const UPDATE_CUSTOM_PRODUCT_SUCCESS = 'UPDATE_CUSTOM_PRODUCT_SUCCESS';
