import { buildOfflineTypes } from '../actions/helpers';

export const LIST_CUSTOMER_CUSTOM_PRODUCTS = buildOfflineTypes('LIST_CUSTOMER_CUSTOM_PRODUCTS');
export const CREATE_CUSTOMER_CUSTOM_PRODUCT_SUCCESS = 'CREATE_CUSTOMER_CUSTOM_PRODUCT_SUCCESS';
export const DELETE_CUSTOMER_CUSTOM_PRODUCT_SUCCESS = 'DELETE_CUSTOMER_CUSTOM_PRODUCT_SUCCESS';
export const UPDATE_CUSTOMER_CUSTOM_PRODUCT_SUCCESS = 'UPDATE_CUSTOMER_CUSTOM_PRODUCT_SUCCESS';
