import { buildOfflineTypes } from '../actions/helpers';

export const LIST_CUSTOMER_PRODUCTS = buildOfflineTypes('LIST_CUSTOMER_PRODUCTS');
export const CREATE_CUSTOMER_PRODUCT_SUCCESS = 'CREATE_CUSTOMER_PRODUCT_SUCCESS';
export const DELETE_CUSTOMER_PRODUCT_SUCCESS = 'DELETE_CUSTOMER_PRODUCT_SUCCESS';
export const UPDATE_CUSTOMER_PRODUCT_SUCCESS = 'UPDATE_CUSTOMER_PRODUCT_SUCCESS';
export const REMOVE_RECENT_CREATED_CUSTOMER_PRODUCT = 'REMOVE_RECENT_CREATED_CUSTOMER_PRODUCT';
