import { buildOfflineTypes } from '../actions/helpers';

export const LIST_CUSTOMER_RETURN_PRODUCTS = buildOfflineTypes('LIST_CUSTOMER_RETURN_PRODUCTS');
export const CREATE_CUSTOMER_RETURN_PRODUCT_SUCCESS = 'CREATE_CUSTOMER_RETURN_PRODUCT_SUCCESS';
export const DELETE_CUSTOMER_RETURN_PRODUCT_SUCCESS = 'DELETE_CUSTOMER_RETURN_PRODUCT_SUCCESS';
export const UPDATE_CUSTOMER_RETURN_PRODUCT_SUCCESS = 'UPDATE_CUSTOMER_RETURN_PRODUCT_SUCCESS';
