import { buildOfflineTypes } from '../actions/helpers';

export const LIST_DEALER_DISCOUNTS = buildOfflineTypes('LIST_DEALER_DISCOUNTS');
export const CREATE_DEALER_DISCOUNT_SUCCESS = 'CREATE_DEALER_DISCOUNT_SUCCESS';
export const UPDATE_DEALER_DISCOUNT_SUCCESS = 'UPDATE_DEALER_DISCOUNT_SUCCESS';
export const DELETE_DEALER_DISCOUNT_SUCCESS = 'DELETE_DEALER_DISCOUNT_SUCCESS';
