import { buildOfflineTypes } from '../actions/helpers';

export const LIST_DELAY_PRODUCTS = buildOfflineTypes('LIST_DELAY_PRODUCTS');
export const CREATE_DELAY_PRODUCT_SUCCESS = 'CREATE_DELAY_PRODUCT_SUCCESS';
export const UPDATE_DELAY_PRODUCT_SUCCESS = 'UPDATE_DELAY_PRODUCT_SUCCESS';
export const DELETE_DELAY_PRODUCT_SUCCESS = 'DELETE_DELAY_PRODUCT_SUCCESS';
export const GET_DELAY_PRODUCT_SUCCESS = 'GET_DELAY_PRODUCT_SUCCESS';
