import { buildOfflineTypes } from '../actions/helpers';

export const LIST_DELIVERY_RECEIPT = buildOfflineTypes('LIST_DELIVERY_RECEIPT');
export const CREATE_DELIVERY_RECEIPT_SUCCESS = 'CREATE_DELIVERY_RECEIPT_SUCCESS';
export const UPDATE_DELIVERY_RECEIPT_SUCCESS = 'UPDATE_DELIVERY_RECEIPT_SUCCESS';
export const DELETE_DELIVERY_RECEIPT_SUCCESS = 'DELETE_DELIVERY_RECEIPT_SUCCESS';
