import { buildOfflineTypes } from '../actions/helpers';

export const LIST_DISCOUNT_PACKAGES = buildOfflineTypes('LIST_DISCOUNT_PACKAGES');
export const CREATE_DISCOUNT_PACKAGE_SUCCESS = 'CREATE_DISCOUNT_PACKAGE_SUCCESS';
export const UPDATE_DISCOUNT_PACKAGE_SUCCESS = 'UPDATE_DISCOUNT_PACKAGE_SUCCESS';
export const DELETE_DISCOUNT_PACKAGE_SUCCESS = 'DELETE_DISCOUNT_PACKAGE_SUCCESS';
export const LIST_DISCOUNT_REPORTS = buildOfflineTypes('LIST_DISCOUNT_REPORTS');
export const DOWANLOAD_DISCOUNT_REPORT = 'DOWANLOAD_DISCOUNT_REPORT';
