import { buildOfflineTypes } from '../actions/helpers';

export const LIST_FINANCE_METHODS = buildOfflineTypes('LIST_FINANCE_METHODS');
export const CREATE_FINANCE_METHOD_SUCCESS = 'CREATE_FINANCE_METHOD_SUCCESS';
export const UPDATE_FINANCE_METHOD_SUCCESS = 'UPDATE_FINANCE_METHOD_SUCCESS';
export const DELETE_FINANCE_METHOD_SUCCESS = 'DELETE_FINANCE_METHOD_SUCCESS';
export const GET_FINANCE_METHOD_SUCCESS = 'GET_FINANCE_METHOD_SUCCESS';
