import { buildOfflineTypes } from '../actions/helpers';

export const LIST_INTEREST_CHARGES = buildOfflineTypes('LIST_INTEREST_CHARGES');
export const CREATE_INTEREST_CHARGE_SUCCESS = 'CREATE_INTEREST_CHARGE_SUCCESS';
export const UPDATE_INTEREST_CHARGE_SUCCESS = 'UPDATE_INTEREST_CHARGE_SUCCESS';
export const DELETE_INTEREST_CHARGE_SUCCESS = 'DELETE_INTEREST_CHARGE_SUCCESS';
