import { buildOfflineTypes } from '../actions/helpers';

export const LIST_PRODUCT_DEALERS = buildOfflineTypes('LIST_PRODUCT_DEALERS');
export const CREATE_PRODUCT_DEALER_SUCCESS = 'CREATE_PRODUCT_DEALER_SUCCESS';
export const UPDATE_PRODUCT_DEALER_SUCCESS = 'UPDATE_PRODUCT_DEALER_SUCCESS';
export const DELETE_PRODUCT_DEALER_SUCCESS = 'DELETE_PRODUCT_DEALER_SUCCESS';
