import { buildOfflineTypes } from '../actions/helpers';

export const LIST_PRODUCT_PACKAGINGS = buildOfflineTypes('LIST_PRODUCT_PACKAGINGS');
export const CREATE_PRODUCT_PACKAGING_SUCCESS = 'CREATE_PRODUCT_PACKAGING_SUCCESS';
export const UPDATE_PRODUCT_PACKAGING_SUCCESS = 'UPDATE_PRODUCT_PACKAGING_SUCCESS';
export const DELETE_PRODUCT_PACKAGING_SUCCESS = 'DELETE_PRODUCT_PACKAGING_SUCCESS';
