import { buildOfflineTypes } from '../actions/helpers';

export const LIST_PURCHASE_ORDER_STATEMENTS = buildOfflineTypes('LIST_PURCHASE_ORDER_STATEMENTS');
export const CREATE_PURCHASE_ORDER_STATEMENT_SUCCESS = 'CREATE_PURCHASE_ORDER_STATEMENT_SUCCESS';
export const UPDATE_PURCHASE_ORDER_STATEMENT_SUCCESS = 'UPDATE_PURCHASE_ORDER_STATEMENT_SUCCESS';
export const DELETE_PURCHASE_ORDER_STATEMENT_SUCCESS = 'DELETE_PURCHASE_ORDER_STATEMENT_SUCCESS';
