import { buildOfflineTypes } from '../actions/helpers';

export const LIST_SEED_COMPANIES = buildOfflineTypes('LIST_SEED_COMPANIES');
export const CREATE_SEED_COMPANY_SUCCESS = 'CREATE_SEED_COMPANY_SUCCESS';
export const UPDATE_SEED_COMPANY_SUCCESS = 'UPDATE_SEED_COMPANY_SUCCESS';
export const DELETE_SEED_COMPANY_SUCCESS = 'DELETE_SEED_COMPANY_SUCCESS';
