import { buildOfflineTypes } from '../actions/helpers';

export const LIST_SHAREHOLDERS = buildOfflineTypes('LIST_SHAREHOLDERS');
export const CREATE_SHAREHOLDER_SUCCESS = 'CREATE_SHAREHOLDER_SUCCESS';
export const DELETE_SHAREHOLDER_SUCCESS = 'DELETE_SHAREHOLDER_SUCCESS';
export const UPDATE_SHAREHOLDER_SUCCESS = 'UPDATE_SHAREHOLDER_SUCCESS';
