import { buildOfflineTypes } from '../actions/helpers';

export const LIST_STATEMENT_SETTINGS = buildOfflineTypes('LIST_STATEMENT_SETTINGS');
export const CREATE_STATEMENT_SETTING_SUCCESS = 'CREATE_STATEMENT_SETTING_SUCCESS';
export const UPDATE_STATEMENT_SETTING_SUCCESS = 'UPDATE_STATEMENT_SETTING_SUCCESS';
export const DELETE_STATEMENT_SETTING_SUCCESS = 'DELETE_STATEMENT_SETTING_SUCCESS';
export const GET_STATEMENT_SETTING_SUCCESS = 'GET_STATEMENT_SETTING_SUCCESS';
