import { buildOfflineTypes } from '../actions/helpers';

export const LIST_STATEMENTS = buildOfflineTypes('LIST_STATEMENTS');
export const CREATE_STATEMENT_SUCCESS = 'CREATE_STATEMENT_SUCCESS';
export const UPDATE_STATEMENT_SUCCESS = 'UPDATE_STATEMENT_SUCCESS';
export const DELETE_STATEMENT_SUCCESS = 'DELETE_STATEMENT_SUCCESS';
export const GET_STATEMENT_SUCCESS = 'GET_STATEMENT_SUCCESS';
export const CREATE_STATEMENTS_SUCCESS = 'CREATE_STATEMENTS_SUCCESS';
