swagger: "2.0"
info:
  description: "AgriDealer API"
  version: 0.1.0
  title: "AgriDealer"
  # termsOfService: "http://swagger.io/terms/"
  contact:
    email: "sourabh.chakraborty@gmail.com"
  license:
    name: "Private License"
    # url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/api"
tags:
- name: "user"
  description: "User operations"
  # externalDocs:
  #   description: "Find out more"
  #   url: "http://swagger.io"
- name: "customer"
  description: "Customer operations"
- name: "custom_product"
  description: "Custom product operations"
schemes:
# - "https"
- "http"
produces: 
- "application/json"
paths:
  /users/{id}:
    parameters:
      - name: "id"
        in: "path"
        description: "User id"
        required: true
        type: "integer"
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "Get use details.  Only same user, or admin users can do this"
      responses:
        default:
          description: "successful operation"
      security: 
      - api_key: []
    patch:
      tags:
      - "user"
      summary: "Update user"
      description: "Update a user.  Only same user or admin can do this"
      responses:
        default:
          description: "successful operation"
      parameters:
      - in: "body"
        name: "body"
        description: "User update object"
        required: true
        schema:
          $ref: "#/definitions/User"
      security: 
      - api_key: []
  /customers:
    get:
      tags: 
      - "customer"
      summary: "Get all customers"
      description: "Returns a list of customers"
      responses:
        200:
          description: OK
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Customer"
      security: 
      - api_key: []
    post:
      tags: 
      - "customer"
      summary: "Create customer"
      description: "Creates a customer"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Customer"
      security: 
      - api_key: []
  /customers/{id}:
    parameters:
      - name: "id"
        in: "path"
        description: "Customer id"
        required: true
        type: "integer"
    delete:
      tags:
      - "customer"
      summary: "Delete a customer"
      description: "Delete a customer"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/OkResponse"
      security: 
      - api_key: []
    patch:
      tags:
      - "customer"
      summary: "Updates a customer"
      description: "Updates a customer"
      parameters:
        - name: "body"
          in: "body"
          description: "A customer update object"
          required: true
          schema:
            $ref: "#/definitions/Customer"
      responses:
        200:
          description: OK
      security: 
      - api_key: []
  /custom_products:
    get:
      tags: 
      - "custom_product"
      summary: "Get all custom products"
      description: "Get all custom products"
      responses:
        200:
          description: OK
          schema:
            type: "array"
            items:
              $ref: "#/definitions/CustomProduct"
      security: 
      - api_key: []
    post:
      tags: 
      - "custom_product"
      summary: "Create a custom product"
      description: "Create a custom product"
      parameters: 
        - name: "body"
          in: "body"
          description: "Custom product to create"
          required: true
          schema:
            $ref: '#/definitions/CustomProduct'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/CustomProduct'
      security: 
      - api_key: []
  /products:
    get:
      summary: "Get products"
      description: "Get products by seed type"
      parameters:
        - name: "seedType"
          in: "query"
          description: "Seed type, one of: CORN, SORGHUM, SOYBEAN"
          required: true
          type: "string"
      responses:
        200:
          description: OK
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Product'
      security: 
      - api_key: []
  /dealer_discounts:
    get:
      summary: "Get dealer discounts"
      description: "Get all dealer discounts"
      responses:
        200:
          description: OK
          schema:
            type: "array"
            items:
              $ref: '#/definitions/DealerDiscount'
      security: 
      - api_key: []
    post:
      summary: "Create a dealer discount"
      description: "Create a dealer discount"
      parameters: 
        - name: "body"
          in: "body"
          description: "Dealer discount to create"
          required: true
          schema:
            $ref: '#/definitions/DealerDiscount'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/DealerDiscount'
      security: 
      - api_key: []
  /dealer_discounts/{id}:
    parameters: 
      - name: "id"
        in: "path"
        required: true
        type: "integer"
    delete:
      summary: "Delete dealer discount"
      description: "Delete a dealer discount"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/OkResponse"
      security: 
      - api_key: []
  /customer_products:
    get:
      summary: "Get all customer products"
      description: "Get all customer products"
      responses:
        200:
          description: OK
          schema:
            type: "array"
            items:
              $ref: '#/definitions/CustomerProduct'
      security: 
      - api_key: []
  
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-token"
    in: "header"
definitions:
  CustomerProduct:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      CustomerId:
        type: "integer"
        format: "int64"
      ProductId:
        type: "integer"
        format: "int64"
      orderQty:
        type: "integer"
        format: "int32"
      Product:
        $ref: '#/definitions/Product'
  DealerDiscount:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      productCategory:
        type: "string"
      name:
        type: "string"
      lastDate:
        type: "string"
      discountStrategy:
        type: "string"
        format: "date"
      detail:
        type: "string"
        format: "jsonb"
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      seedType:
        type: "string"
      brand:
        type: "string"
      blend:
        type: "string"
      seedSize:
        type: "string"
      treatment:
        type: "string"
      quantity:
        type: "integer"
        format: "int32"
      msrp:
        type: "number"
        format: "price"
      amountPerBag:
        type: "string"
        
  CustomProduct:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      description:
        type: "string"
      unit:
        type: "string"
      costUnit:
        type: "string"
      quantity:
        type: "integer"
        format: "int32"
  Customer:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      organizationName:
        type: "string"
      email:
        type: "string"
      phoneNumber:
        type: "string"
      deliveryAddress:
        type: "string"
      businessAddress:
        type: "string"
      monsantoTechnologyId:
        type: "string"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
  OkResponse:
    type: "object"
    properties:
      ok:
        type: "string"
