import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import PropTypes from 'prop-types';

import PurchaseOrder from './purchase_order_new_api';

import { LoadingStatus } from '../../store/constants';
import {
  listCustomers,
  listProducts,
  listCustomerProducts,
  createCustomerProduct,
  editCustomerProduct,
  deleteCustomerProduct,
  listCustomerMonsantoProducts,
  createCustomerMonsantoProduct,
  editCustomerMonsantoProduct,
  updateQuoteMonsantoProduct,
  deleteCustomerMonsantoProduct,
  listDealerDiscounts,
  listAllCustomProducts,
  listCustomerCustomProducts,
  createCustomerCustomProduct,
  deleteCustomerCustomProduct,
  updateCustomerCustomProduct,
  listPurchaseOrders,
  updatePurchaseOrder,
  syncMonsantoOrders,
  deletePurchaseOrder,
  convertQuoteToExistingPurchaseOrder,
  listDeliveryReceipts,
  createDeliveryReceipt,
  createPurchaseOrderForCustomer,
  listDiscountPackages,
  listPackagings,
  listSeedSizes,
  listFarms,
  createFarm,
  updateFarm,
  deleteFarm,
  listShareholders,
  createShareholder,
  getPdfForPage,
  listPayments,
  createPayment,
  updatePayment,
  deletePayment,
  loadOrganization,
  listProductPackagings,
  removeRecentCreatedCustomerProduct,
  getPurchaseOrderById,
  updateProductPackaging,
  createProductPackaging,
  checkProductAvailability,
  createNote,
  updateNote,
  makeProductOrderBooking,
  listSeedCompanies,
  listCompanies,
  createDiscounReport,
  listCustomerAllReturnProducts,
  checkinOrderProductAvailability,
  getCustomerShareholders,
} from '../../store/actions';

const mapStateToProps = (state) => {
  return {
    totalItemsOfCustomers: state.customerReducer.totalItems,
    currentPurchaseOrder: state.purchaseOrderReducer.current,
    currentPurchaseOrderLoadingStatus: state.purchaseOrderReducer.currentLoadingStatus,
    noFound: state.purchaseOrderReducer.noFound,
    customersStatus: state.customerReducer.loadingStatus,
    customers: state.customerReducer.customers,
    business: state.customProductReducer.products,
    products: state.productReducer.products,
    monsantoProducts: state.monsantoProductReducer.monsantoProducts,
    customProducts: state.customProductReducer.products,

    productsStatus: state.productReducer.loadingStatus,
    dealerDiscounts: state.dealerDiscountReducer.dealerDiscounts,
    dealerDiscountsStatus: state.dealerDiscountReducer.loadingStatus,
    companies: state.companyReducer.companies,
    seedCompanies: state.seedCompanyReducer.seedCompanies,
    apiSeedCompanies: state.apiSeedCompanyReducer.apiSeedCompanies,
    items: state.purchaseOrderReducer.purchaseOrders,
    itemsStatus: state.purchaseOrderReducer.loadingStatus,
    deliveryReceipts: state.deliveryReceiptReducer.deliveryReceipts,
    deliveryReceiptsStatus: state.deliveryReceiptReducer.loadingStatus,
    relatedProducts: state.customerProductReducer.customerProducts,
    recentCreatedCustomerProductId: state.customerProductReducer.recentCreatedCustomerProductId,
    relatedProductsStatus: state.customerProductReducer.loadingStatus,
    relatedCustomProducts: state.customerCustomProductReducer.customerCustomProducts,
    relatedCustomProductsStatus: state.customerCustomProductReducer.loadingStatus,
    discountPackages: state.discountPackageReducer.discountPackages,
    discountPackagesStatus: state.discountPackageReducer.loadingStatus,
    packagings: state.packagingReducer.packagings,
    seedSizes: state.seedSizeReducer.seedSizes,
    farms: state.farmReducer.farms,
    shareholders: state.shareholderReducer.shareholders,
    packagingsStatus: state.packagingReducer.loadingStatus,
    payments: state.paymentReducer.payments,
    organizationId: state.userReducer.organizationId,
    organization: state.organizationReducer,
    productPackagings: state.productPackagingReducer.productPackagings,
    productPackagingsStatus: state.productPackagingReducer.loadingStatus,
    isOnline: state.offline.online,
    isAdmin: state.userReducer.isAdmin,
    customerReturnProducts: state.customerReturnProductReducer.customerReturnProducts,

    getCustomerOrders: function () {
      const { purchaseOrder } = this.state;
      const { relatedProducts, relatedCustomProducts, match } = this.props;

      const customerOrders = relatedProducts.filter((rp) => rp.customerId.toString() === match.params.customer_id);
      const customProductOrders = relatedCustomProducts.filter(
        (rcp) => rcp.customerId.toString() === match.params.customer_id,
      );

      return customerOrders.concat(customProductOrders).filter((orders) => orders.purchaseOrderId === purchaseOrder.id);
    },
  };
};

const mapDispatchToProps = (dispatch) =>
  bindActionCreators(
    {
      listCustomers,
      listProducts,
      listAllCustomProducts,
      listRelatedProducts: listCustomerProducts,
      linkRelatedProduct: createCustomerProduct,
      editRelatedProduct: editCustomerProduct,
      removeRelatedProduct: deleteCustomerProduct,
      syncMonsantoOrders,
      listRelatedMonsantoProducts: listCustomerMonsantoProducts,
      linkRelatedMonsantoProduct: createCustomerMonsantoProduct,
      editRelatedMonsantoProduct: editCustomerMonsantoProduct,
      removeRelatedMonsantoProduct: deleteCustomerMonsantoProduct,
      updateQuoteMonsantoProduct: updateQuoteMonsantoProduct,
      checkProductAvailability,
      listCustomerAllReturnProducts,
      listDealerDiscounts,
      listRelatedCustomProducts: listCustomerCustomProducts,
      linkRelatedCustomProduct: createCustomerCustomProduct,
      removeRelatedCustomProduct: deleteCustomerCustomProduct,
      editRelatedCustomProduct: updateCustomerCustomProduct,
      listPurchaseOrders,
      updatePurchaseOrder,
      deletePurchaseOrder,
      convertQuoteToExistingPurchaseOrder,
      listDeliveryReceipts,
      linkDeliveryReceipt: createDeliveryReceipt,
      createItemForCustomer: createPurchaseOrderForCustomer,
      removeItemForCustomer: deletePurchaseOrder,
      listDiscountPackages,
      listPackagings,
      listSeedSizes,
      listFarms,
      createFarm,
      updateFarm,
      deleteFarm,
      listShareholders,
      createShareholder,
      getPdfForPage,
      listPayments,
      createPayment,
      updatePayment,
      deletePayment,
      loadOrganization,
      listProductPackagings,
      removeRecentCreatedCustomerProduct,
      getPurchaseOrderById,
      updateProductPackaging,
      createProductPackaging,
      createNote,
      updateNote,
      makeProductOrderBooking,
      listSeedCompanies,
      listCompanies,
      createDiscounReport,
      checkinOrderProductAvailability,
      getCustomerShareholders,
    },
    dispatch,
  );

PurchaseOrder.displayName = 'PurchaseOrder';
PurchaseOrder.propTypes = {
  subjectName: PropTypes.string,
  products: PropTypes.array,
  productsStatus: PropTypes.oneOf(Object.values(LoadingStatus)),
  business: PropTypes.array,
  dealerDiscounts: PropTypes.array,
  dealerDiscountsStatus: PropTypes.oneOf(Object.values(LoadingStatus)),
  companies: PropTypes.array,
  apiSeedCompanies: PropTypes.array,
  items: PropTypes.array,
  cloneItem: PropTypes.func,
  listDeliveryReceipts: PropTypes.func,
  linkDeliveryReceipt: PropTypes.func,
  listRelatedProducts: PropTypes.func.isRequired,
  linkRelatedProduct: PropTypes.func.isRequired,
  editRelatedProduct: PropTypes.func.isRequired,
  listProducts: PropTypes.func.isRequired,
  removeRelatedProduct: PropTypes.func.isRequired,
  listDealerDiscounts: PropTypes.func.isRequired,
  listAllCustomProducts: PropTypes.func.isRequired,
  listRelatedCustomProducts: PropTypes.func.isRequired,
  linkRelatedCustomProduct: PropTypes.func.isRequired,
  removeRelatedCustomProduct: PropTypes.func.isRequired,
  listPurchaseOrders: PropTypes.func.isRequired,
  updatePurchaseOrder: PropTypes.func.isRequired,
  createItemForCustomer: PropTypes.func.isRequired,

  // provided by withStyles HoC
  // classes: PropTypes.object.isRequired
};
export default connect(mapStateToProps, mapDispatchToProps)(PurchaseOrder);
