import { buildOfflineTypes } from '../../actions/helpers';

export const LIST_MONSANTO_PRODUCTS = buildOfflineTypes('LIST_MONSANTO_PRODUCTS');
export const UPDATE_MONSANTO_PRODUCT_CURRENT_SEED_COMPANY_ID = 'UPDATE_MONSANTO_PRODUCT_CURRENT_SEED_COMPANY_ID';
export const UPDATE_MONSANTO_PRODUCT_CURRENT_CROP_TYPE = 'UPDATE_MONSANTO_PRODUCT_CURRENT_CROP_TYPE';

export const UPDATE_MONSANTO_PRODUCT_CURRENT_ZONE_IDS = 'UPDATE_MONSANTO_PRODUCT_CURRENT_ZONE_IDS';
export const UPDATE_MONSANTO_PRODUCT = 'UPDATE_MONSANTO_PRODUCT';
