import { buildOfflineTypes } from '../../actions/helpers';

export const LIST_MONSANTO_RETAILER_SUMMARY = buildOfflineTypes('LIST_MONSANTO_RETAILER_SUMMARY');
export const UPDATE_ROS_CURRENT_SEED_COMPANY_ID = 'UPDATE_ROS_CURRENT_SEED_COMPANY_ID';
export const UPDATE_ROS_CURRENT_CROP_TYPE = 'UPDATE_ROS_CURRENT_CROP_TYPE';
export const UPDATE_MONSANTO_RETAILER_SUMMARY_FILTERS = 'UPDATE_MONSANTO_RETAILER_SUMMARY_FILTERS';
