import { buildOfflineTypes } from '../../actions/helpers';

export const LIST_MONSANTO_FAVORITE_PRODUCTS = buildOfflineTypes('LIST_MONSANTO_FAVORITE_PRODUCTS');
export const CREATE_MONSANTO_FAVORITE_PRODUCT_SUCCESS = 'CREATE_MONSANTO_FAVORITE_PRODUCT_SUCCESS';
export const DELETE_MONSANTO_FAVORITE_PRODUCT_SUCCESS = 'DELETE_MONSANTO_FAVORITE_PRODUCT_SUCCESS';
